# fly.toml app configuration file generated for ai-assistant-lead-gen-owl-homes on 2025-04-30T08:22:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-assistant-lead-gen-owl-homes'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
